#!/bin/bash

i=0;
while read line; do
	dirname=`echo ${line//./ }`;
	dirname=${dirname%%DC*};	
	dirname=${dirname%%Franchise*};	
	dirname=${dirname%%(*};
	dirname=${dirname%%[*};
	dirname=${dirname%%DVD*};
	dirname=${dirname%%DirCut*};
	dirname=${dirname%%XviD*};
	dirname=${dirname%%Criterion*};
	dirname=${dirname%%Trilogy*};
	dirname=${dirname%%Rip*};
	dirname=${dirname%%BD*};
	dirname=${dirname%%BR*};
	dirname=${dirname%%720p*};
	dirname=${dirname%%1080p*};
	dirname=${dirname%%Extended*};
	dirname=${dirname%%m-HD*};
	dirname=${dirname%%DvDrip*};
	dirname=${dirname%%BluRay*};
	dirname=${dirname%%480p*};
	dirname=${dirname%%PROPER*};
	dirname=${dirname%%EXTENDED*};
	dirname=${dirname%%Remastered*};
	dirname=${dirname%%HDTV*};
	dirname=${dirname%%list*};
	dirname=${dirname%%Movie*};
	if [[ -z "${dirname// }" ]]; then
		do_nothing=1;
	else
		mkdir -v "$dirname"; 
		mv "$dirname" "movie_dirs";	
	fi
done < movie_list
